version: "2"
services:

  nginx:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    container_name: nginx

  backserver:
    build: .
    environment:
      VIRTUAL_HOST: ${HOSTNAME}.backend.dev
    volumes:
    - "${BACKEND_PATH}:/var/www"
    container_name: backend_webserver

  frontserver:
    build: .
    environment:
      VIRTUAL_HOST: ${HOSTNAME}.frontend.dev
    volumes:
    - "${FRONTEND_PATH}:/src/app"
    container_name: frontend_webserver
    ports:
    - "35729:35729"
    - "3030:3000"

  db:
    image: mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'drupal'
    ports:
    - "3307:3306"
    volumes:
    -
    container_name: mysql_server

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  mailhog:
      image: mailhog/mailhog
      ports:
        - "8002:8025"

#  redis:
#    image: redis:3.2-alpine

#  memcached:
#    image: memcached:1.4-alpine

#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
#    ports:
#      - "8003:8983"

#  varnish:
#    image: wodby/drupal-varnish
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#      VARNISH_MEMORY_SIZE: 256M
#      VARNISH_STORAGE_SIZE: 1024M
#    ports:
#      - "8004:6081" # HTTP Proxy
#      - "8005:6082" # Control terminal
